services:

  oracle:
    image: gvenzl/oracle-xe:21-slim
    container_name: oracle-db
    volumes:
      - oracle-data:/opt/oracle/oradata
    ports:
      - 1521:1521
    environment:
      ORACLE_PASSWORD: root

volumes:
   oracle-data: